### ISSUE TITLE
ES6 integration

### ISSUE THREAD

**Issue by ingelity** [awslabs/aws-sam-local#150] opened 2017-09-29 15:14 UTC
Sorry for opening an issue but don't know where else could I've sent the question.
How can I use aws-sam-local with ES6 code? 
I tried requiring babel-register in my handler file but it seems to have issues with docker or something...
Any ideas?

**Comment by perrygeorget** [comment] 2017-10-19 00:22
We too use ES6 code via babel.  We using serverless to package and deploy our lambda via cloudformation.  We leverage webpack via [serverless-webpack](https://www.npmjs.com/package/serverless-plugin-webpack), but would love to use sam for local development.

In future, it would be nice if sam had a serverless plugin of some sort replacing [serverless-offline](https://www.npmjs.com/package/serverless-offline) fully which is going into retirement.

Can you at least create some example or help me to create some example of this working with webpack?

**Comment by sanathkr** [comment] 2017-10-19 00:27
SAM local should work irrespective of ES5/6, as long as the language runtime (nodejs4.3, 6.10) supports the features. You should have a make/gulp/grunt system that can convert and package your code for you in format that Lambda can run. If you combine gulp with `gulp-watch`, you can easily `gulp dev` script that can watch for files, run babel on changed files, and output to a `build` directory. In your SAM template just point Lambda CodeUri to the build directory and everything should work.

What is not quite working for you? Do you want an example on how to `gulp dev` in background along with SAM Local?

**Comment by perrygeorget** [comment] 2017-10-19 17:00
An example on how to gulp dev in background along with SAM Local would be nice.  Thank you in advance.

I will have to create a sample (non-proprietary) application and puts it to a public repo which is the base example of how we developer out API Gateway serverless applications and a bit of things specific to this application.

The log output from SAM CLI was:

```
2017/10/18 18:44:27 Invoking tmp/handlers/lambda.handler (nodejs6.10)
2017/10/18 18:44:27 Invalid environment override file sam-env.json: json: cannot unmarshal number into Go value of type string
START RequestId: 67a3a25f-9616-1001-d4d7-98f12c963066 Version: $LATEST
2017-10-19T01:44:29.753Z	67a3a25f-9616-1001-d4d7-98f12c963066	AWS_XRAY_DAEMON_ADDRESS is set. Configured daemon address to #.#.#.#:2000.
2017-10-19T01:44:29.755Z	67a3a25f-9616-1001-d4d7-98f12c963066	AWS_XRAY_CONTEXT_MISSING is set. Configured context missing strategy to LOG_ERROR.
2017-10-19T01:44:29.758Z	67a3a25f-9616-1001-d4d7-98f12c963066	Subsegment streaming threshold set to: 0
2017-10-19T01:44:29.855Z	67a3a25f-9616-1001-d4d7-98f12c963066	raven@1.2.1 alert: no DSN provided, error reporting disabled
2017-10-19T01:44:30.129Z	67a3a25f-9616-1001-d4d7-98f12c963066	raven@1.2.1 alert: no DSN provided, error reporting disabled
2017-10-19T01:44:30.131Z	67a3a25f-9616-1001-d4d7-98f12c963066	raven@1.2.1 alert: Enabled automatic breadcrumbs for console
2017-10-19T01:44:30.132Z	67a3a25f-9616-1001-d4d7-98f12c963066	raven@1.2.1 alert: Enabled automatic breadcrumbs for http
2017-10-19T01:44:30.133Z	67a3a25f-9616-1001-d4d7-98f12c963066	raven@1.2.1 alert: Enabled automatic breadcrumbs for pg
END RequestId: 67a3a25f-9616-1001-d4d7-98f12c963066
REPORT RequestId: 67a3a25f-9616-1001-d4d7-98f12c963066	Duration: 1882.26 ms	Billed Duration: 0 ms	Memory Size: 0 MB	Max Memory Used: 281 MB
2017/10/18 18:44:30 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character '{' after top-level value
```

We pre-compiled the ES6 code using serverless-webpack via

```
sls webpack -o tmp/
```

We ran by executing

```
sam local start-api --template sam.yml --env-vars sam-env.json --port 4000
```

Our `sam.yml` file roughly contained:

```yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.
Resources:
  GraphQLServer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tmp/handlers/lambda.handler
      Runtime: nodejs6.10
      Events:
        GetGraphQL:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
        PostGraphQL:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
        GetGraphiQL:
          Type: Api
          Properties:
            Path: /graphiql
            Method: any`
```

Our `sam-env.json` file does contain values that are strings, numbers and booleans. Given the output above those may have caused notable issues.

It would seem that imports are occurring properly, but for some reason that is unlogged execution is bailing.

**Comment by perrygeorget** [comment] 2017-10-19 17:13
After making sure that all values in `sam-env.json` were string.  No change in the failure.

**Comment by perrygeorget** [comment] 2017-10-20 21:19
Good news! For my specific issue I figured it out.  The problem is that [bunyan]() has been streaming to stdout via `process.stdout`.  I take that `STDOUT` is the conduit by which the response from ones callback from the lambda is translated into the aws-sam-local's response.

This produces a new challenge of how do you configure bunyan for use with aws-sam-local?

It would be good to make a serverless plugin that translates their configuration into aws-sam's expected format.  I think if serverless-offline was forked or something similar created (i.e. serverless-sam) it would be great as serverless-offline is approaching end of life.

**Comment by purefan** [comment] 2017-10-23 06:33
> how do you configure bunyan for use with aws-sam-local?
> It would be good to make a serverless plugin that translates their configuration into aws-sam

I would submit this to Bunyan's channels

**Comment by PaulMaddox** [comment] 2017-10-27 13:00
Closing this issue down as it doesn't sound like a bug with SAM Local.

**Closed by PaulMaddox** 2017-10-27 13:00 UTC
