### ISSUE TITLE
Docker client and server API version out of sync

### ISSUE THREAD

**Issue by ellery44** [awslabs/aws-sam-local#115] opened 2017-09-09 17:19 UTC
Not sure if this is issue with sam or some thing else on my system but thought id start here. Ive followed all install instructions and everything seems fine till I try and run the lambda functions locally. Im getting the following error when running `sam local start-api`

```
2017/09/09 10:14:39 Connected to Docker
2017/09/09 10:14:39 Successfully parsed template.yml
2017/09/09 10:14:39 Ignoring index.handler due to nodejs6.10 runtime init error: Error response from daemon: client is newer than server (client API version: 1.30, server API version: 1.24)
ERROR: None of the Serverless functions in your SAM template were able to be mounted. See above for errors.
``` 
My docker versions seem fine and I can run other containers.
`docker version`
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   78d1802
 Built:        Tue Mar 14 09:47:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   78d1802
 Built:        Tue Mar 14 09:47:15 2017
 OS/Arch:      linux/amd64
```
`docker run hello-world`
```
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```
I'm not sure where client version API version 1.3.0 is even coming from. Any ideas?

**Comment by PaulMaddox** [comment] 2017-09-12 08:55
SAM Local has the Docker client SDK bundled with it (to communicate with the docker daemon), and the bundled version is 1.3.0 (hence the version you're seeing).

This is a duplicate of #97 - check that issue for how to resolve it (upgrade docker), or a workaround that should work without upgrading.

**Closed by PaulMaddox** 2017-09-12 08:55 UTC
