### ISSUE TITLE
Context object invoked_arn incomplete

### ISSUE THREAD

**Issue by apmclean** [awslabs/aws-sam-local#52] opened 2017-08-16 01:08 UTC
In Lambda I extract the region the function is running in for various purposes (mostly for creating a boto3 sessions for building clients, assuming roles etc).

eg: 
```python
def determine_region(context):

    m = re.match("arn:aws:lambda:(.*?):\d+.*$", context.invoked_function_arn)
    if m:
        return(m.group(1))
```

SAM Local doesn't appear to include a region in the arn.  I get something like:
`arn:aws:lambda::104260451092:function:test`

I haven't found anywhere I can set the region for the context object in the template.yaml file.  Have I missed something?

Thanks!

**Comment by sanathkr** [comment] 2017-08-16 02:01
Good question. I need to dig deeper to find where the ARN is created and set. I think it comes from Docker container.

**Comment by sanathkr** [comment] 2017-08-16 05:30
This is a dupe of #48. In docker-lambda, ARN is constructed by concatenating accountId, region, and function name here https://github.com/lambci/docker-lambda/blob/master/python2.7/run/runtime-mock.py#L51. But due to #48, region is not available in Docker container due to some reason.

I will close this Issue now. Feel free to track #48 for updates.

**Closed by sanathkr** 2017-08-16 05:30 UTC
Labels: bug
