### ISSUE TITLE
Cloudformation Templates

### ISSUE THREAD

**Issue by jenkink** [awslabs/aws-sam-local#88] opened 2017-08-23 14:45 UTC
Is there a way to use this with functions using AWS::Lambda::Function or it is only AWS::Serverless::Function?

**Comment by sanathkr** [comment] 2017-08-23 14:56
Not at the moment, but we are very very close. #83 puts us just one step away from using AWS::Lambda::Function. Stay tuned! 

I am going to close this one as a dupe of https://github.com/awslabs/aws-sam-local/issues/18. Please follow this Issue for updates

**Closed by sanathkr** 2017-08-23 14:56 UTC
