### ISSUE TITLE
Add support for Go runtime

### ISSUE THREAD

**Issue by sgarcez** [awslabs/aws-sam-local#264] opened 2018-01-17 14:02 UTC
Now that support for Golang in Lambda has been [announced](https://aws.amazon.com/blogs/compute/announcing-go-support-for-aws-lambda/) it would be great to see the new `go1.x` runtime also supported in SAM local.

I presume that a reasonable approach would be to use a linux based container to run a pre-built Go binary, but I haven't looked into the current runtime integrations in much detail yet. One requirement there would be for the binary to be compiled with a linux target of course.

I might have time to work on this, unless someone else is already on it.

**Comment by christianklotz** [comment] 2018-01-17 17:13
All runtimes are using `lambci/lambda:*` images and it seems like @mhart has [already started working](/lambci/docker-lambda/issues/65#issuecomment-358015789) on the Go runtime 🎉.

https://github.com/awslabs/aws-sam-local/blob/bd1672469e85bf533ee10849773ee7c92a854411/runtime.go#L93-L100

**Comment by sanathkr** [comment] 2018-01-17 17:59
mhart is already working on it. Once he adds the Go containers, we will make it available in SAM Local

**Comment by bscott** [comment] 2018-01-18 22:57
Can't wait!

**Comment by mtojek** [comment] 2018-01-21 18:17
@sgarcez in the mean time you can use the proxy to pass all Lambda events:
https://github.com/mtojek/aws-lambda-go-proxy

**Comment by terrywarwar** [comment] 2018-01-22 04:57
@mhart added a PR, https://github.com/lambci/docker-lambda/pull/67

**Comment by PaulMaddox** [comment] 2018-01-23 06:37
Reopening this. @mhart, i'm seeing an issue when testing with the runtime.

```
```

**Comment by mhart** [comment] 2018-01-23 13:28
The fact that it's timing out immediately makes me think that `AWS_LAMBDA_FUNCTION_TIMEOUT` is set incorrectly somewhere?

**Comment by PaulMaddox** [comment] 2018-01-23 14:19
Yes, that looks like the case.  The template I was testing with didn't specifically set a timeout value, so it should have defaulted to 3 seconds.

The codepath that handles halting function execution in SAM Local works correctly in this case, and defaults to 3 seconds, however if a timeout is not specified in the SAM template, then `AWS_LAMBDA_FUNCTION_TIMEOUT` is not set.

I'll fix this, but I'm surprised this didn't cause issues before with other runtimes.

**Comment by mhart** [comment] 2018-01-23 14:27
Well it not being set should default it to 300 seconds (in docker-lambda that is) – so it must be specifically set to something else? Is it an empty string perhaps?

Maybe I should adjust https://github.com/lambci/docker-lambda/blob/master/go1.x/run/aws-lambda-mock.go#L193-L198 so that it returns the default on empty strings too

**Comment by mhart** [comment] 2018-01-23 14:35
(I've done exactly that – it will now fallback on empty strings – building on docker hub now. Not sure if that was what was going on in this case, but I think it's the right thing to do regardless)

**Comment by mhart** [comment] 2018-01-23 15:12
(Building has finished – feel free to retry and see if that changed anything – again, not entirely sure an empty string is the cause... but it might be!)

**Comment by lancerushing** [comment] 2018-01-23 19:46
Maybe related. I'm installing sam-local on a new box.  npm has the new release number **0.2.5** but github doesn't have the release yet.
```bash
$ npm install -g aws-sam-local

> aws-sam-local@0.2.5 postinstall /opt/node-v6.9.5-linux-x64/lib/node_modules/aws-sam-local
> go-npm install

Downloading from URL: https://github.com/awslabs/aws-sam-local/releases/download/v0.2.5/sam_0.2.5_linux_amd64.tar.gz
Error downloading binary. HTTP Status Code: 404
```
When I check https://github.com/awslabs/aws-sam-local/releases , I don't see the release.

**Comment by terrywarwar** [comment] 2018-01-24 04:21
v0.2.6 works fine with both `sam local invoke` and `sam local start-api`

**Comment by PaulMaddox** [comment] 2018-01-24 06:28
Awesome - closing this issue now. Thanks for your help everyone!

**Closed by PaulMaddox** 2018-01-24 06:28 UTC

**Comment by tausif-citrusPay** [comment] 2018-02-08 14:49
Did anyone try debugging on JetBrains GoLand?

**Comment by uccmen** [comment] 2018-04-10 05:15
does `aws-sam-local local start-api` hot reloads for changes in .go files? or is this feature for Go not supported yet?

**Comment by terrywarwar** [comment] 2018-04-10 05:17
@uccmen you have to `go build` your changes.

**Comment by aripalo** [comment] 2018-08-26 12:53
This thread suggest that the Golang is now implemented into SAM CLI, but the README does not state that: https://github.com/awslabs/aws-sam-cli#project-status 

Is it just a missing info on README or is there still some functionality missing related to Golang support? I'm, just currently considering Lambda+Golang and figuring out all the options for development etc 🙂

**Comment by piotrkubisa** [comment] 2018-08-26 17:20
@aripalo Haha, good catch. I suppose population of developers reading documentation/README thoroughly decreases each day by some percents :smile: I've added #631 as PR regarding this issue.
